web: bundle exec unicorn_rails -p $PORT -E development -c config/unicorn_development.rb
worker: sudo -u git -i bash -c 'cd $STACK_PATH && bundle exec sidekiq -q post_receive -q mailer -q system_hook -q project_web_hook -q gitlab_shell -q common -q default -e $RAILS_ENV'
custom_web: bundle exec unicorn_rails -c config/unicorn.rb.cloud66 -E $RAILS_ENV -D




